numeros = set([1, 2, 3, 4, 5, 4, 6, 7, 8, 9, 2, 8, 9, 2, 3,])
fruta = set("abacaxi")
carros = set(("palio", "celta", "palio", "uno", "up"))
print(numeros)
print(fruta)
print(carros)
linguagues = ("python", "java", "go", "r", "python", "js")
print(linguagues)